name: Waka Readme

on:
  schedule:
    # Runs at the end of every day
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ### content
          SHOW_TITLE: true 
          SECTION_NAME: waka 
          BLOCKS: -> 
          CODE_LANG: rust 
          TIME_RANGE: all_time 
          LANG_COUNT: 10 
          SHOW_TIME: true 
          SHOW_TOTAL: true 
          SHOW_MASKED_TIME: false 
          STOP_AT_OTHER: true 
          IGNORED_LANGUAGES: YAML JSON TOML 
          ### commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics 
          TARGET_BRANCH: main 
          TARGET_PATH: README.md 
          COMMITTER_NAME: GitHubActionBot 
          COMMITTER_EMAIL: action-bot@github.com 
          AUTHOR_NAME: Shashikant Solanki 
